### ISSUE TITLE
manage.html - some error

### ISSUE THREAD

**Issue by vrsz** [malsf21/prefects-cup-website#3]
after i edit manage.html with my firebase api key, i got this error:
{"error":{"code":400,"message":"API key expired. Please renew the API key.","errors":[{"message":"API key expired. Please renew the API key.","domain":"global","reason":"badRequest"}],"status":"INVALID_ARGUMENT"}}

**Comment by mattxwang** [comment]
Yeah, so as it says in the error message your API key is expired. Get a new one from the Firebase website, and it should work.

**Comment by vrsz** [comment]
Thank you, solved.
